In [13]:
import pandas as pd
import numpy as np

df = pd.read_csv(r"C:\Users\LENOVO\Desktop\customer-churn-prediction\data\customer_churn_cleaned.csv")

df.shape

(1000000, 31)

In [ ]:
# Splitting the data into training and testing sets

from sklearn.model_selection import train_test_split

X = df.drop(columns=["churn"])
y = df["churn"]

X_train, X_test, y_train, y_test = train_test_split(X,y,
test_size=0.20,random_state=42,stratify=y)

print("X_train:", X_train.shape)
print("X_test :", X_test.shape)
print("y_train:", y_train.shape)
print("y_test :", y_test.shape)

X_train: (800000, 30)
X_test : (200000, 30)
y_train: (800000,)
y_test : (200000,)

In [16]:
print("X shape:", X.shape)
print("y shape:", y.shape)

X shape: (1000000, 30)
y shape: (1000000,)

In [ ]:
# Selecting numerical and categorical columns

numeric_cols = X_train.select_dtypes(include="number").columns.tolist()
categorical_cols = X_train.select_dtypes(include="str").columns.tolist()

print("Numerical columns:")
print(numeric_cols)

print("\nCategorical columns:")
print(categorical_cols)

Numerical columns:
['age', 'annual_income', 'dependents', 'tenure', 'senior_citizen', 'monthlycharges', 'totalcharges', 'num_services', 'has_phone_service', 'has_internet_service', 'has_online_security', 'has_online_backup', 'has_device_protection', 'has_tech_support', 'has_streaming_tv', 'has_streaming_movies', 'customer_satisfaction', 'num_complaints', 'num_service_calls', 'late_payments', 'avg_monthly_gb', 'days_since_last_interaction', 'credit_score']

Categorical columns:
['signup_date', 'gender', 'education', 'marital_status', 'contract', 'payment_method', 'paperless_billing']

In [19]:
df["signup_date"].dtypes

In [ ]:
# Converting signup_date to datetime

X_train["signup_date"] = pd.to_datetime(X_train["signup_date"])
X_test["signup_date"] = pd.to_datetime(X_test["signup_date"])

print(X_train["signup_date"].dtype)
print(X_test["signup_date"].dtype)

datetime64[us]
datetime64[us]

In [ ]:
#  Extracting year from signup date

X_train["signup_year"] = X_train["signup_date"].dt.year
X_test["signup_year"] = X_test["signup_date"].dt.year

print(X_train["signup_year"].value_counts().sort_index())

signup_year
2021    154465
2022    160098
2023    159994
2024    160902
2025    159776
2026      4765
Name: count, dtype: int64

In [ ]:
# Extracting month from signup date

X_train["signup_month"] = X_train["signup_date"].dt.month
X_test["signup_month"] = X_test["signup_date"].dt.month

print(X_train["signup_month"].value_counts().sort_index())

signup_month
1     67725
2     62221
3     67722
4     65192
5     68156
6     65445
7     68098
8     68100
9     66032
10    68073
11    65391
12    67845
Name: count, dtype: int64

In [24]:
# Dropping the original signup_date column

X_train = X_train.drop(columns=["signup_date"])
X_test = X_test.drop(columns=["signup_date"])

print(X_train.shape)
print(X_test.shape)

(800000, 31)
(200000, 31)

In [ ]:
# conforming categorical columns after feature engineering

categorical_cols = X_train.select_dtypes(include="str").columns.tolist()

print(categorical_cols)

['gender', 'education', 'marital_status', 'contract', 'payment_method', 'paperless_billing']

In [ ]:
# Selecting numerical and categorical columns
numeric_cols = X_train.select_dtypes(include="number").columns.tolist()

print("Number of numerical columns:", len(numeric_cols))
print("Number of categorical columns:", len(categorical_cols))

Number of numerical columns: 25
Number of categorical columns: 6

In [27]:
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline

In [ ]:
# Creating a pipeline for numerical features

numeric_pipeline = Pipeline(steps=[
    ("imputer", SimpleImputer(strategy="median")),
    ("scaler", StandardScaler())
])

In [29]:
# Creating a pipeline for categorical features

categorical_pipeline = Pipeline(steps=[
    ("imputer", SimpleImputer(strategy="most_frequent")),
    ("encoder", OneHotEncoder(handle_unknown="ignore"))
])

In [30]:
# Combining the numerical and categorical pipelines into a single preprocessor

preprocessor = ColumnTransformer(
    transformers=[
        ("num", numeric_pipeline, numeric_cols),
        ("cat", categorical_pipeline, categorical_cols)
    ]
)

In [31]:
# Processing the training data

X_train_processed = preprocessor.fit_transform(X_train)

In [32]:
# Processing the testing data

X_test_processed = preprocessor.transform(X_test)

In [ ]:
print("X_train_processed shape:", X_train_processed.shape)
print("X_test_processed shape :", X_test_processed.shape)

X_train_processed shape: (800000, 46)
X_test_processed shape : (200000, 46)

In [ ]:
# Checking for missing values in the processed data

print("Missing values in X_train_processed:",
      np.isnan(X_train_processed).sum())

print("Missing values in X_test_processed:",
      np.isnan(X_test_processed).sum())

Missing values in X_train_processed: 0
Missing values in X_test_processed: 0

In [35]:
# Getting feature names after preprocessing
feature_names = preprocessor.get_feature_names_out()

print("Number of features:", len(feature_names))
print(feature_names)

Number of features: 46
['num__age' 'num__annual_income' 'num__dependents' 'num__tenure'
 'num__senior_citizen' 'num__monthlycharges' 'num__totalcharges'
 'num__num_services' 'num__has_phone_service' 'num__has_internet_service'
 'num__has_online_security' 'num__has_online_backup'
 'num__has_device_protection' 'num__has_tech_support'
 'num__has_streaming_tv' 'num__has_streaming_movies'
 'num__customer_satisfaction' 'num__num_complaints'
 'num__num_service_calls' 'num__late_payments' 'num__avg_monthly_gb'
 'num__days_since_last_interaction' 'num__credit_score' 'num__signup_year'
 'num__signup_month' 'cat__gender_Female' 'cat__gender_Male'
 'cat__gender_Other' 'cat__education_bachelor' 'cat__education_college'
 'cat__education_high_school' 'cat__education_master' 'cat__education_phd'
 'cat__marital_status_divorced' 'cat__marital_status_married'
 'cat__marital_status_single' 'cat__marital_status_widowed'
 'cat__contract_month_to_month' 'cat__contract_one_year'
 'cat__contract_two_year' 'cat__payment_method_bank_transfer'
 'cat__payment_method_credit_card' 'cat__payment_method_electronic_check'
 'cat__payment_method_mailed_check' 'cat__paperless_billing_No'
 'cat__paperless_billing_Yes']

In [36]:
print("y_train shape:", y_train.shape)
print("y_test shape :", y_test.shape)

print("\nTraining target distribution:")
print(y_train.value_counts())

y_train shape: (800000,)
y_test shape : (200000,)

Training target distribution:
churn
0    720618
1     79382
Name: count, dtype: int64

In [ ]:
import joblib

joblib.dump(preprocessor, "../models/preprocessor.joblib")

['../models/preprocessor.joblib']

Logistic Regression

In [ ]:
# Fitting the logistic regression model to the processed training data

from sklearn.linear_model import LogisticRegression

logistic_model = LogisticRegression(
    class_weight="balanced",
    random_state=42,
    max_iter=1000
)

In [ ]:
# Fitting the logistic regression model to the processed training data

logistic_model.fit(X_train_processed, y_train)

LogisticRegression(class_weight='balanced', max_iter=1000, random_state=42)

In [ ]:
# Making predictions on the processed testing data

y_pred = logistic_model.predict(X_test_processed)

print(y_pred[:20])

[0 0 1 1 1 0 1 1 0 1 0 1 0 1 0 0 0 1 1 0]

In [41]:
# Evaluating the model's performance using a confusion matrix

from sklearn.metrics import confusion_matrix

cm = confusion_matrix(y_test, y_pred)

print(cm)

[[112849  67306]
 [  7155  12690]]

In [42]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score

accuracy = accuracy_score(y_test, y_pred)
precision = precision_score(y_test, y_pred)
recall = recall_score(y_test, y_pred)
f1 = f1_score(y_test, y_pred)

print("Accuracy :", accuracy)
print("Precision:", precision)
print("Recall   :", recall)
print("F1 Score :", f1)

Accuracy : 0.627695
Precision: 0.15863293164658232
Recall   : 0.6394557823129252
F1 Score : 0.25420418465359923

In [43]:
from sklearn.metrics import classification_report

print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.94      0.63      0.75    180155
           1       0.16      0.64      0.25     19845

    accuracy                           0.63    200000
   macro avg       0.55      0.63      0.50    200000
weighted avg       0.86      0.63      0.70    200000

Random Forest

In [ ]:
# Fitting the random forest model to the processed training data

from sklearn.ensemble import RandomForestClassifier

rf_model = RandomForestClassifier(
    n_estimators=100,
    class_weight="balanced",
    random_state=42,
    n_jobs=-1
)

In [45]:
# Fitting the random forest model to the processed training data

rf_model.fit(X_train_processed, y_train)

RandomForestClassifier(class_weight='balanced', n_jobs=-1, random_state=42)

In [46]:
y_pred_rf = rf_model.predict(X_test_processed)

print(y_pred_rf[:20])

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]

In [47]:
from sklearn.metrics import confusion_matrix

cm_rf = confusion_matrix(y_test, y_pred_rf)

print(cm_rf)

[[179146   1009]
 [ 19279    566]]

In [48]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score

accuracy_rf = accuracy_score(y_test, y_pred_rf)
precision_rf = precision_score(y_test, y_pred_rf)
recall_rf = recall_score(y_test, y_pred_rf)
f1_rf = f1_score(y_test, y_pred_rf)

print("Accuracy :", accuracy_rf)
print("Precision:", precision_rf)
print("Recall   :", recall_rf)
print("F1 Score :", f1_rf)

Accuracy : 0.89856
Precision: 0.3593650793650794
Recall   : 0.02852103804484757
F1 Score : 0.05284780578898226

xgboost

In [49]:
from xgboost import XGBClassifier

In [50]:
xgb_model = XGBClassifier(
    n_estimators=100,
    max_depth=6,
    learning_rate=0.1,
    scale_pos_weight=9.08,
    random_state=42,
    n_jobs=-1,
    eval_metric="logloss"
)

In [51]:
xgb_model.fit(X_train_processed, y_train)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, device=None, early_stopping_rounds=None,
              enable_categorical=True, eval_metric='logloss',
              feature_types=None, feature_weights=None, gamma=None,
              grow_policy=None, importance_type=None,
              interaction_constraints=None, learning_rate=0.1, max_bin=None,
              max_cat_threshold=None, max_cat_to_onehot=None,
              max_delta_step=None, max_depth=6, max_leaves=None,
              min_child_weight=None, missing=nan, monotone_constraints=None,
              multi_strategy=None, n_estimators=100, n_jobs=-1,
              num_parallel_tree=None, ...)

In [52]:
y_pred_xgb = xgb_model.predict(X_test_processed)

print(y_pred_xgb[:20])

[0 0 1 1 0 0 1 0 0 1 0 1 0 1 0 0 0 1 1 0]

In [53]:
from sklearn.metrics import confusion_matrix

cm_xgb = confusion_matrix(y_test, y_pred_xgb)

print(cm_xgb)

[[113930  66225]
 [  7303  12542]]

In [54]:
accuracy_xgb = accuracy_score(y_test, y_pred_xgb)
precision_xgb = precision_score(y_test, y_pred_xgb)
recall_xgb = recall_score(y_test, y_pred_xgb)
f1_xgb = f1_score(y_test, y_pred_xgb)

print("Accuracy :", accuracy_xgb)
print("Precision:", precision_xgb)
print("Recall   :", recall_xgb)
print("F1 Score :", f1_xgb)

Accuracy : 0.63236
Precision: 0.15922911879340332
Recall   : 0.6319979843789367
F1 Score : 0.25437066482781

Create StratifiedKFold

In [55]:
from sklearn.model_selection import StratifiedKFold

cv = StratifiedKFold(
    n_splits=5,
    shuffle=True,
    random_state=42
)

In [61]:
from sklearn.model_selection import cross_validate

cv_results_lr = cross_validate(
    logistic_model,
    X_train_processed,
    y_train,
    cv=cv,
    scoring=["accuracy", "precision", "recall", "f1"],
    n_jobs=-1
)

In [62]:
print("Logistic Regression CV Results")
print("Mean Accuracy :", cv_results_lr["test_accuracy"].mean())
print("Mean Precision:", cv_results_lr["test_precision"].mean())
print("Mean Recall   :", cv_results_lr["test_recall"].mean())
print("Mean F1       :", cv_results_lr["test_f1"].mean())

Logistic Regression CV Results
Mean Accuracy : 0.62836875
Mean Precision: 0.15905815320381372
Mean Recall   : 0.6403340943962748
Mean F1       : 0.2548183138498067

In [56]:
# cross-validation Random Forest

from sklearn.model_selection import cross_validate


cv_results_rf = cross_validate(
    rf_model,
    X_train_processed,
    y_train,
    cv=cv,
    scoring=["accuracy", "precision", "recall", "f1"],
    n_jobs=-1
)

In [57]:
print("Random Forest CV Results")
print("Mean Accuracy :", cv_results_rf["test_accuracy"].mean())
print("Mean Precision:", cv_results_rf["test_precision"].mean())
print("Mean Recall   :", cv_results_rf["test_recall"].mean())
print("Mean F1       :", cv_results_rf["test_f1"].mean())

Random Forest CV Results
Mean Accuracy : 0.89875875
Mean Precision: 0.36397593475501183
Mean Recall   : 0.027147198751526064
Mean F1       : 0.050523447126657725

In [58]:
# cross-validation XGBoost

cv_results_xgb = cross_validate(
    xgb_model,
    X_train_processed,
    y_train,
    cv=cv,
    scoring=["accuracy", "precision", "recall", "f1"],
    n_jobs=-1
)

In [59]:
print("XGBoost CV Results")
print("Mean Accuracy :", cv_results_xgb["test_accuracy"].mean())
print("Mean Precision:", cv_results_xgb["test_precision"].mean())
print("Mean Recall   :", cv_results_xgb["test_recall"].mean())
print("Mean F1       :", cv_results_xgb["test_f1"].mean())

XGBoost CV Results
Mean Accuracy : 0.6350337500000001
Mean Precision: 0.16024811035577974
Mean Recall   : 0.6315285577605735
Mean F1       : 0.2556280386568348

Compare the models

In [64]:

cv_comparison = pd.DataFrame({
    "Model": [
        "Logistic Regression",
        "Random Forest",
        "XGBoost"
    ],
    "Accuracy": [
        cv_results_lr["test_accuracy"].mean(),
        cv_results_rf["test_accuracy"].mean(),
        cv_results_xgb["test_accuracy"].mean()
    ],
    "Precision": [
        cv_results_lr["test_precision"].mean(),
        cv_results_rf["test_precision"].mean(),
        cv_results_xgb["test_precision"].mean()
    ],
    "Recall": [
        cv_results_lr["test_recall"].mean(),
        cv_results_rf["test_recall"].mean(),
        cv_results_xgb["test_recall"].mean()
    ],
    "F1": [
        cv_results_lr["test_f1"].mean(),
        cv_results_rf["test_f1"].mean(),
        cv_results_xgb["test_f1"].mean()
    ]
})

cv_comparison

                 Model  Accuracy  Precision    Recall        F1
0  Logistic Regression  0.628369   0.159058  0.640334  0.254818
1        Random Forest  0.898759   0.363976  0.027147  0.050523
2              XGBoost  0.635034   0.160248  0.631529  0.255628

Hyperparameter tuning

In [65]:
from sklearn.model_selection import RandomizedSearchCV

xgb_param_grid = {
    "n_estimators": [100, 200, 300],
    "max_depth": [3, 5, 7, 9],
    "learning_rate": [0.01, 0.05, 0.1, 0.2],
    "subsample": [0.7, 0.8, 1.0],
    "colsample_bytree": [0.7, 0.8, 1.0],
    "min_child_weight": [1, 3, 5]
}

In [66]:
xgb_random_search = RandomizedSearchCV(
    estimator=xgb_model,
    param_distributions=xgb_param_grid,
    n_iter=10,
    scoring="f1",
    cv=cv,
    random_state=42,
    n_jobs=-1,
    verbose=1
)

In [67]:
xgb_random_search.fit(X_train_processed, y_train)

Fitting 5 folds for each of 10 candidates, totalling 50 fits

RandomizedSearchCV(cv=StratifiedKFold(n_splits=5, random_state=42, shuffle=True),
                   estimator=XGBClassifier(base_score=None, booster=None,
                                           callbacks=None,
                                           colsample_bylevel=None,
                                           colsample_bynode=None,
                                           colsample_bytree=None, device=None,
                                           early_stopping_rounds=None,
                                           enable_categorical=True,
                                           eval_metric='logloss',
                                           feature_types=None,
                                           feature_weights=None, gamma=None,...
                                           min_child_weight=None, missing=nan,
                                           monotone_constraints=None,
                                           multi_strategy=None,
                                           n_estimators=100, n_jobs=-1,
                                           num_parallel_tree=None, ...),
                   n_jobs=-1,
                   param_distributions={'colsample_bytree': [0.7, 0.8, 1.0],
                                        'learning_rate': [0.01, 0.05, 0.1, 0.2],
                                        'max_depth': [3, 5, 7, 9],
                                        'min_child_weight': [1, 3, 5],
                                        'n_estimators': [100, 200, 300],
                                        'subsample': [0.7, 0.8, 1.0]},
                   random_state=42, scoring='f1', verbose=1)

In [68]:
print("Best Parameters:")
print(xgb_random_search.best_params_)

print("\nBest CV F1 Score:")
print(xgb_random_search.best_score_)

Best Parameters:
{'subsample': 0.7, 'n_estimators': 100, 'min_child_weight': 5, 'max_depth': 7, 'learning_rate': 0.05, 'colsample_bytree': 1.0}

Best CV F1 Score:
0.2557525379959901

In [69]:
best_xgb_model = xgb_random_search.best_estimator_

In [70]:
y_pred_xgb_tuned = best_xgb_model.predict(X_test_processed)

In [71]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix

print("Tuned XGBoost Test Results")
print("Accuracy :", accuracy_score(y_test, y_pred_xgb_tuned))
print("Precision:", precision_score(y_test, y_pred_xgb_tuned))
print("Recall   :", recall_score(y_test, y_pred_xgb_tuned))
print("F1       :", f1_score(y_test, y_pred_xgb_tuned))

print("\nConfusion Matrix:")
print(confusion_matrix(y_test, y_pred_xgb_tuned))

Tuned XGBoost Test Results
Accuracy : 0.63061
Precision: 0.1588782686650084
Recall   : 0.6340639959687578
F1       : 0.2540890917168127

Confusion Matrix:
[[113539  66616]
 [  7262  12583]]

In [72]:
best_xgb_model.predict(X_test_processed)

array([0, 0, 1, ..., 0, 0, 0], shape=(200000,))

In [73]:
X_train_model, X_val, y_train_model, y_val = train_test_split(
    X_train_processed,
    y_train,
    test_size=0.20,
    random_state=42,
    stratify=y_train
)

In [74]:
best_xgb_model.fit(X_train_model, y_train_model)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=1.0, device=None, early_stopping_rounds=None,
              enable_categorical=True, eval_metric='logloss',
              feature_types=None, feature_weights=None, gamma=None,
              grow_policy=None, importance_type=None,
              interaction_constraints=None, learning_rate=0.05, max_bin=None,
              max_cat_threshold=None, max_cat_to_onehot=None,
              max_delta_step=None, max_depth=7, max_leaves=None,
              min_child_weight=5, missing=nan, monotone_constraints=None,
              multi_strategy=None, n_estimators=100, n_jobs=-1,
              num_parallel_tree=None, ...)

In [75]:
y_val_proba = best_xgb_model.predict_proba(X_val)[:, 1]

In [76]:
y_val_proba[:10]

array([0.25071153, 0.18207167, 0.45199615, 0.35828987, 0.7313175 ,
       0.6326828 , 0.5539369 , 0.3662707 , 0.5826333 , 0.3428486 ],
      dtype=float32)

In [ ]:
# Compare thresholds

from sklearn.metrics import precision_score, recall_score, f1_score

thresholds = [0.10, 0.20, 0.30, 0.40, 0.50, 0.60, 0.70, 0.80, 0.90]

threshold_results = []

for threshold in thresholds:
    y_val_pred = (y_val_proba >= threshold).astype(int)

    threshold_results.append({
        "Threshold": threshold,
        "Precision": precision_score(y_val, y_val_pred),
        "Recall": recall_score(y_val, y_val_pred),
        "F1": f1_score(y_val, y_val_pred)
    })

threshold_df = pd.DataFrame(threshold_results)

threshold_df

   Threshold  Precision    Recall        F1
0        0.1   0.099232  1.000000  0.180549
1        0.2   0.101504  0.992504  0.184173
2        0.3   0.114034  0.932099  0.203208
3        0.4   0.132233  0.820295  0.227752
4        0.5   0.161234  0.632779  0.256987
5        0.6   0.203205  0.377047  0.264084
6        0.7   0.276543  0.155203  0.198822
7        0.8   0.411672  0.032880  0.060896
8        0.9   0.666667  0.000252  0.000504

In [ ]:
# Find the best threshold more precisely

thresholds_fine = np.arange(0.40, 0.71, 0.01)

fine_results = []

for threshold in thresholds_fine:
    y_val_pred = (y_val_proba >= threshold).astype(int)

    fine_results.append({
        "Threshold": threshold,
        "Precision": precision_score(y_val, y_val_pred),
        "Recall": recall_score(y_val, y_val_pred),
        "F1": f1_score(y_val, y_val_pred)
    })

fine_threshold_df = pd.DataFrame(fine_results)

fine_threshold_df.loc[
    fine_threshold_df["F1"].idxmax()
]

Threshold    0.570000
Precision    0.189331
Recall       0.457168
F1           0.267769
Name: 17, dtype: float64

In [79]:
y_test_proba = best_xgb_model.predict_proba(X_test_processed)[:, 1]

In [80]:
best_threshold = 0.57

y_test_pred_tuned = (y_test_proba >= best_threshold).astype(int)

In [81]:
print("Final XGBoost Test Results")
print("Threshold :", best_threshold)
print("Accuracy  :", accuracy_score(y_test, y_test_pred_tuned))
print("Precision :", precision_score(y_test, y_test_pred_tuned))
print("Recall    :", recall_score(y_test, y_test_pred_tuned))
print("F1        :", f1_score(y_test, y_test_pred_tuned))

print("\nConfusion Matrix:")
print(confusion_matrix(y_test, y_test_pred_tuned))

Final XGBoost Test Results
Threshold : 0.57
Accuracy  : 0.75217
Precision : 0.18996056831695562
Recall    : 0.45880574452003026
F1        : 0.26867917847025496

Confusion Matrix:
[[141329  38826]
 [ 10740   9105]]

In [82]:
final_model_comparison = pd.DataFrame({
    "Model": [
        "Logistic Regression",
        "Random Forest",
        "XGBoost Baseline",
        "XGBoost Tuned",
        "XGBoost Tuned + Threshold 0.57"
    ],
    "Accuracy": [
        accuracy_score(y_test, y_pred),
        accuracy_score(y_test, y_pred_rf),
        accuracy_score(y_test, y_pred_xgb),
        accuracy_score(y_test, y_pred_xgb_tuned),
        accuracy_score(y_test, y_test_pred_tuned)
    ],
    "Precision": [
        precision_score(y_test, y_pred),
        precision_score(y_test, y_pred_rf),
        precision_score(y_test, y_pred_xgb),
        precision_score(y_test, y_pred_xgb_tuned),
        precision_score(y_test, y_test_pred_tuned)
    ],
    "Recall": [
        recall_score(y_test, y_pred),
        recall_score(y_test, y_pred_rf),
        recall_score(y_test, y_pred_xgb),
        recall_score(y_test, y_pred_xgb_tuned),
        recall_score(y_test, y_test_pred_tuned)
    ],
    "F1": [
        f1_score(y_test, y_pred),
        f1_score(y_test, y_pred_rf),
        f1_score(y_test, y_pred_xgb),
        f1_score(y_test, y_pred_xgb_tuned),
        f1_score(y_test, y_test_pred_tuned)
    ]
})

final_model_comparison

                            Model  Accuracy  Precision    Recall        F1
0             Logistic Regression  0.627695   0.158633  0.639456  0.254204
1                   Random Forest  0.898560   0.359365  0.028521  0.052848
2                XGBoost Baseline  0.632360   0.159229  0.631998  0.254371
3                   XGBoost Tuned  0.630610   0.158878  0.634064  0.254089
4  XGBoost Tuned + Threshold 0.57  0.752170   0.189961  0.458806  0.268679

In [83]:
import joblib

joblib.dump(best_xgb_model, "../models/xgb_churn_model.joblib")

['../models/xgb_churn_model.joblib']

In [84]:
joblib.dump(best_threshold, "../models/churn_threshold.joblib")

['../models/churn_threshold.joblib']

In [85]:
import joblib

loaded_preprocessor = joblib.load("../models/preprocessor.joblib")
loaded_model = joblib.load("../models/xgb_churn_model.joblib")
loaded_threshold = joblib.load("../models/churn_threshold.joblib")

print("Preprocessor loaded:", type(loaded_preprocessor))
print("Model loaded:", type(loaded_model))
print("Threshold:", loaded_threshold)

Preprocessor loaded: <class 'sklearn.compose._column_transformer.ColumnTransformer'>
Model loaded: <class 'xgboost.sklearn.XGBClassifier'>
Threshold: 0.57

In [86]:
best_xgb_model.fit(
    X_train_processed,
    y_train
)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=1.0, device=None, early_stopping_rounds=None,
              enable_categorical=True, eval_metric='logloss',
              feature_types=None, feature_weights=None, gamma=None,
              grow_policy=None, importance_type=None,
              interaction_constraints=None, learning_rate=0.05, max_bin=None,
              max_cat_threshold=None, max_cat_to_onehot=None,
              max_delta_step=None, max_depth=7, max_leaves=None,
              min_child_weight=5, missing=nan, monotone_constraints=None,
              multi_strategy=None, n_estimators=100, n_jobs=-1,
              num_parallel_tree=None, ...)

In [87]:
joblib.dump(
    best_xgb_model,
    "../models/xgb_churn_model.joblib"
)

['../models/xgb_churn_model.joblib']

Final sanity check

In [88]:
y_test_proba_final = best_xgb_model.predict_proba(X_test_processed)[:, 1]

y_test_pred_final = (
    y_test_proba_final >= best_threshold
).astype(int)

In [89]:
print("Final Model Test Results")
print("Threshold :", best_threshold)
print("Accuracy  :", accuracy_score(y_test, y_test_pred_final))
print("Precision :", precision_score(y_test, y_test_pred_final))
print("Recall    :", recall_score(y_test, y_test_pred_final))
print("F1        :", f1_score(y_test, y_test_pred_final))

print("\nConfusion Matrix:")
print(confusion_matrix(y_test, y_test_pred_final))

Final Model Test Results
Threshold : 0.57
Accuracy  : 0.750475
Precision : 0.18970642883686362
Recall    : 0.46303854875283446
F1        : 0.26914458942928693

Confusion Matrix:
[[140906  39249]
 [ 10656   9189]]